DELETE_OPACITY_THRESHOLD = 0.1
DENSIFY_GRAD_THRESHOLD = 0.0001
CLONE_SCALE_THRESHOLD = 0.02

USE_SPLIT = True
USE_CLONE = True
USE_DELETE = True

BASE_LR = 0.004
XYZ_LR_MULTIPLIER = 0.1
QUAT_LR_MULTIPLIER = 1
SCALE_LR_MULTIPLIER = 10
OPACITY_LR_MULTIPLIER = 10
RGB_LR_MULTIPLIER = 10

CULL_MASK_PADDING = 100
NUM_ITERS = 7000

PRINT_DEBUG_TIMING = False
