# (TODO move these to an options struct for reproducability)

INITIAL_OPACITY = 0.2  # initial opacity value (sigmoid activation)
INITIAL_SCALE_NUM_NEIGHBORS = 3  # number of neighbors used to compute initial scale
INITIAL_SCALE_FACTOR = 0.8  # scaling factor for initial scale:  log(mean_neighbor_dist * factor = initial_scale)

DELETE_OPACITY_THRESHOLD = 0.1
DENSIFY_GRAD_THRESHOLD = 0.00008
CLONE_SCALE_THRESHOLD = 0.02

NEAR_THRESH = 0.3
MH_DIST = 3.0

USE_SPLIT = True
USE_CLONE = True
USE_DELETE = True
ADAPTIVE_CONTROL_START = 1000
ADAPTIVE_CONTROL_END = 5000
ADAPTIVE_CONTROL_INVERVAL = 100

BASE_LR = 0.004
XYZ_LR_MULTIPLIER = 0.1
QUAT_LR_MULTIPLIER = 1
SCALE_LR_MULTIPLIER = 10
OPACITY_LR_MULTIPLIER = 10
RGB_LR_MULTIPLIER = 10

CULL_MASK_PADDING = 100
NUM_ITERS = 7000

SSIM_RATIO = 0.2

PRINT_DEBUG_TIMING = False

SATURATED_PIXEL_VALUE = 255.0

SAVE_DEBUG_IMAGE_INTERVAL = 50
PRINT_INTERVAL = 10

TEST_SPLIT_RATIO = 10
TEST_EVAL_INTERVAL = 200
